#!/usr/bin/env node
/**
 * Verifies the JavaScript engine port (engine.js) against the vectors generated by the Java
 * BoardEngine (engine-vectors.json, a copy of docs/engine/engine-vectors.json).
 *
 * For every case the port must reproduce the initial board, the replay result (validity, score,
 * moves, boosters, objective, stars) and the final board; the RNG sequence is checked as well.
 * Usage: `node verify-engine.mjs [path/to/engine-vectors.json]`. Exits with 1 on any mismatch.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { BoardState, SeededRandom, greedySolve, simulate } from './engine.js';

const here = dirname(fileURLToPath(import.meta.url));
const vectorsPath = resolve(process.argv[2] || resolve(here, 'engine-vectors.json'));

/** Renders a board as compact rows for readable diffs. */
function formatBoard(board) {
  return board.map((row) => row.join(' ')).join('\n');
}

/** Deep equality for the plain arrays/objects used by the vectors. */
function sameJson(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

/** Compares one scalar field and records a human readable mismatch. */
function expectEqual(problems, field, actual, expected) {
  if (actual !== expected) {
    problems.push(`${field}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
}

/** Checks the raw RNG sequence of the top-level `rng` block. */
function verifyRng(rng) {
  const random = new SeededRandom(rng.seed);
  const actual = rng.expected.map(() => random.nextInt(rng.bound));
  if (!sameJson(actual, rng.expected)) {
    return [`rng sequence: expected ${JSON.stringify(rng.expected)}, got ${JSON.stringify(actual)}`];
  }
  return [];
}

/** Runs one vector case through the port and returns the list of mismatches (empty = pass). */
function verifyCase(c) {
  const problems = [];

  const initial = new BoardState(c.config, c.seed).snapshot();
  if (!sameJson(initial, c.initialBoard)) {
    problems.push(`initial board differs:\n--- expected\n${formatBoard(c.initialBoard)}\n--- actual\n${formatBoard(initial)}`);
  }

  const result = simulate(c.config, c.seed, c.moves, c.extraMovesUsed);
  expectEqual(problems, 'valid', result.valid, c.valid);
  expectEqual(problems, 'finalScore', result.score, c.finalScore);
  expectEqual(problems, 'finalMovesUsed', result.movesUsed, c.finalMovesUsed);
  expectEqual(problems, 'hammersUsed', result.hammersUsed, c.hammersUsed);
  expectEqual(problems, 'shufflesUsed', result.shufflesUsed, c.shufflesUsed);
  expectEqual(problems, 'objectiveReached', result.objectiveReached, c.objectiveReached);
  expectEqual(problems, 'stars', result.stars, c.stars);
  if (!sameJson(result.board, c.finalBoard)) {
    problems.push(`final board differs:\n--- expected\n${formatBoard(c.finalBoard)}\n--- actual\n${formatBoard(result.board)}`);
  }

  // Vectors that consist purely of TAP moves without boosters were produced by the Java
  // GreedySolver, so the JS solver must pick exactly the same cells in the same order.
  const tapOnly = c.moves.every((m) => m.type === 'TAP');
  if (c.valid && tapOnly && !c.extraMovesUsed) {
    const solved = greedySolve(c.config, c.seed);
    if (!sameJson(solved.moves, c.moves)) {
      problems.push(`greedySolve moves differ:\n--- expected\n${JSON.stringify(c.moves)}\n--- actual\n${JSON.stringify(solved.moves)}`);
    }
    expectEqual(problems, 'greedySolve.score', solved.score, c.finalScore);
    expectEqual(problems, 'greedySolve.movesUsed', solved.movesUsed, c.finalMovesUsed);
    expectEqual(problems, 'greedySolve.objectiveReached', solved.objectiveReached, c.objectiveReached);
  }
  return problems;
}

/** Entry point: loads the vectors, runs every check and prints a summary. */
function main() {
  const vectors = JSON.parse(readFileSync(vectorsPath, 'utf8'));
  console.log(`Verifying engine.js against ${vectorsPath}`);
  console.log(`${vectors.description}\n`);

  const rngProblems = verifyRng(vectors.rng);
  const rngFailed = rngProblems.length > 0;
  if (rngFailed) {
    console.log(`FAIL rng (seed=${vectors.rng.seed}, bound=${vectors.rng.bound})\n  ${rngProblems.join('\n  ')}`);
  } else {
    console.log(`PASS rng sequence (seed=${vectors.rng.seed}, bound=${vectors.rng.bound}, ${vectors.rng.expected.length} values)`);
  }

  let caseFailures = 0;
  let solverChecked = 0;
  vectors.cases.forEach((c, index) => {
    const problems = verifyCase(c);
    const summary = `case ${String(index).padStart(2, ' ')}: ${c.config.rows}x${c.config.cols} colours=${c.config.colorCount} ` +
      `seed=${c.seed} extraMoves=${c.extraMovesUsed} moves=${c.moves.length} ` +
      `-> valid=${c.valid} score=${c.finalScore} stars=${c.stars}`;
    if (c.valid && c.moves.every((m) => m.type === 'TAP') && !c.extraMovesUsed) {
      solverChecked++;
    }
    if (problems.length > 0) {
      caseFailures++;
      console.log(`FAIL ${summary}\n  ${problems.join('\n  ')}`);
    } else {
      console.log(`PASS ${summary}`);
    }
  });

  const total = vectors.cases.length;
  const failures = caseFailures + (rngFailed ? 1 : 0);
  console.log(`\n${total - caseFailures} of ${total} cases passed, ${failures} failure(s) ` +
    `(rng sequence ${rngFailed ? 'FAILED' : 'ok'}, greedy solver cross-checked on ${solverChecked} TAP-only cases).`);
  process.exit(failures === 0 ? 0 : 1);
}

main();
