using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace BlastScale.Client.Audio
{
    /// <summary>Every sound effect the game can play (clips are generated by <see cref="SoundSynth"/>).</summary>
    public enum Sfx
    {
        UiClick,
        Pop,
        Invalid,
        Whoosh,
        CoinTick,
        CoinBurst,
        StarChime,
        WinJingle,
        LoseSting,
        ComboSwell,
        BoosterUse
    }

    /// <summary>
    /// Plays effects through a small pool of AudioSources (so overlapping pops never cut each
    /// other off) and loops the ambient music. Music and effects can be muted from the home
    /// screen; the choice is remembered in PlayerPrefs ("blastscale.music", "blastscale.sfx").
    /// A singleton created by the bootstrap; <see cref="Play(Sfx,float,float)"/> is safe to call
    /// before it exists (it simply does nothing).
    ///
    /// <para>Real music files are optional: when <c>Resources/Audio/music_main</c>,
    /// <c>Resources/Audio/jingle_win</c> or <c>Resources/Audio/jingle_lose</c> exist they replace
    /// the synthesised loop and jingles (see <see cref="MusicResource"/>); the UI and gameplay
    /// effects stay synthesised. A file jingle ducks the music while it plays. Without the files
    /// everything is generated at startup exactly as before.</para>
    ///
    /// <para>The music starts once at boot (login screen) and keeps looping through home, gameplay
    /// and result; screens never restart it, and muting pauses instead of stopping so unmuting
    /// resumes where it was.</para>
    /// </summary>
    public sealed class AudioManager : MonoBehaviour
    {
        public const string MusicPrefKey = "blastscale.music";
        public const string SfxPrefKey = "blastscale.sfx";

        /// <summary>Resources paths (no extension) of the optional real music and jingles.</summary>
        public const string MusicResource = "Audio/music_main";
        public const string WinJingleResource = "Audio/jingle_win";
        public const string LoseJingleResource = "Audio/jingle_lose";

        private const float MusicVolume = 0.35f;

        /// <summary>A produced track is mixed louder than the thin synthesised pad.</summary>
        private const float MusicFileVolume = 0.45f;

        private const float SfxVolume = 0.8f;
        private const int SfxSourceCount = 8;

        /// <summary>While a file jingle plays the music drops to 40 % for two seconds, then eases back.</summary>
        private const float DuckLevel = 0.4f;
        private const float DuckSeconds = 2f;
        private const float DuckFadeOutSeconds = 0.15f;
        private const float DuckFadeInSeconds = 0.8f;

        private static AudioManager _instance;

        private readonly Dictionary<Sfx, AudioClip> _clips = new Dictionary<Sfx, AudioClip>();
        private readonly HashSet<Sfx> _fileJingles = new HashSet<Sfx>();
        private readonly List<AudioSource> _sfxSources = new List<AudioSource>();
        private AudioSource _musicSource;
        private AudioClip _music;
        private AudioClip _musicFile;
        private float _musicBaseVolume = MusicVolume;
        private bool _musicPaused;
        private Coroutine _duckRoutine;
        private int _nextSource;
        private bool _musicEnabled;
        private bool _sfxEnabled;

        public static AudioManager Instance => _instance;

        /// <summary>Creates the manager (and synthesises every clip) once; returns the existing one afterwards.</summary>
        public static AudioManager Ensure()
        {
            if (_instance == null)
            {
                var go = new GameObject("AudioManager");
                _instance = go.AddComponent<AudioManager>();
                _instance.Initialise();
            }
            return _instance;
        }

        /// <summary>Fire-and-forget effect; <paramref name="pitch"/> multiplies the clip's pitch.</summary>
        public static void Play(Sfx sfx, float pitch = 1f, float volume = 1f)
        {
            if (_instance != null)
            {
                _instance.PlayInternal(sfx, pitch, volume);
            }
        }

        /// <summary>Pop sound whose pitch grows with the group size (bigger groups sound brighter).</summary>
        public static void PlayPop(int groupSize)
        {
            float pitch = Mathf.Clamp(0.9f + (groupSize - 2) * 0.06f, 0.9f, 1.8f);
            Play(Sfx.Pop, pitch);
        }

        public bool MusicEnabled
        {
            get => _musicEnabled;
            set
            {
                _musicEnabled = value;
                PlayerPrefs.SetInt(MusicPrefKey, value ? 1 : 0);
                PlayerPrefs.Save();
                ApplyMusicState();
            }
        }

        public bool SfxEnabled
        {
            get => _sfxEnabled;
            set
            {
                _sfxEnabled = value;
                PlayerPrefs.SetInt(SfxPrefKey, value ? 1 : 0);
                PlayerPrefs.Save();
            }
        }

        /// <summary>The clip the music source loops (null until <see cref="StartMusic"/> ran); tests check it never changes.</summary>
        public AudioClip MusicClip => _music;

        /// <summary>True when a real track from Resources/Audio replaced the synthesised loop.</summary>
        public bool MusicIsFromFile => _musicFile != null;

        /// <summary>True while the loop is audibly playing (false when muted or before StartMusic).</summary>
        public bool IsMusicPlaying => _musicSource != null && _musicSource.isPlaying;

        /// <summary>Playback position of the loop in seconds; keeps growing across screens when nothing restarts it.</summary>
        public float MusicTime => _musicSource != null ? _musicSource.time : 0f;

        /// <summary>Starts the ambient loop (respecting the mute preference); idempotent, never restarts a running loop.</summary>
        public void StartMusic()
        {
            if (_music == null)
            {
                _music = _musicFile != null ? _musicFile : SoundSynth.MusicLoop();
                _musicBaseVolume = _musicFile != null ? MusicFileVolume : MusicVolume;
                _musicSource.clip = _music;
                _musicSource.loop = true;
                _musicSource.volume = _musicBaseVolume;
            }
            ApplyMusicState();
        }

        private void Initialise()
        {
            EnsureAudioListener();
            _musicEnabled = PlayerPrefs.GetInt(MusicPrefKey, 1) == 1;
            _sfxEnabled = PlayerPrefs.GetInt(SfxPrefKey, 1) == 1;

            _clips[Sfx.UiClick] = SoundSynth.UiClick();
            _clips[Sfx.Pop] = SoundSynth.Pop();
            _clips[Sfx.Invalid] = SoundSynth.Invalid();
            _clips[Sfx.Whoosh] = SoundSynth.Whoosh();
            _clips[Sfx.CoinTick] = SoundSynth.CoinTick();
            _clips[Sfx.CoinBurst] = SoundSynth.CoinBurst();
            _clips[Sfx.StarChime] = SoundSynth.StarChime();
            _clips[Sfx.WinJingle] = SoundSynth.WinJingle();
            _clips[Sfx.LoseSting] = SoundSynth.LoseSting();
            _clips[Sfx.ComboSwell] = SoundSynth.ComboSwell();
            _clips[Sfx.BoosterUse] = SoundSynth.BoosterUse();
            LoadOptionalFiles();

            for (int i = 0; i < SfxSourceCount; i++)
            {
                var source = gameObject.AddComponent<AudioSource>();
                source.playOnAwake = false;
                source.spatialBlend = 0f;
                _sfxSources.Add(source);
            }
            _musicSource = gameObject.AddComponent<AudioSource>();
            _musicSource.playOnAwake = false;
            _musicSource.spatialBlend = 0f;
        }

        /// <summary>
        /// Picks up real audio files dropped into Resources/Audio (any format Unity imports:
        /// .ogg, .mp3, .wav). Each one silently replaces its synthesised counterpart; missing
        /// files change nothing.
        /// </summary>
        private void LoadOptionalFiles()
        {
            _musicFile = Resources.Load<AudioClip>(MusicResource);
            if (_musicFile != null)
            {
                Debug.Log("[audio] Using " + MusicResource + " as the music loop");
            }
            AudioClip win = Resources.Load<AudioClip>(WinJingleResource);
            if (win != null)
            {
                _clips[Sfx.WinJingle] = win;
                _fileJingles.Add(Sfx.WinJingle);
            }
            AudioClip lose = Resources.Load<AudioClip>(LoseJingleResource);
            if (lose != null)
            {
                _clips[Sfx.LoseSting] = lose;
                _fileJingles.Add(Sfx.LoseSting);
            }
        }

        /// <summary>
        /// Unity plays nothing at all when the scene has no <see cref="AudioListener"/> — it is the
        /// microphone of the scene. The generated scene carries one on the camera, but this runtime
        /// guarantee keeps sound working in a scene that was built or edited without it (which is
        /// exactly how the first device build ended up completely silent).
        /// </summary>
        private static void EnsureAudioListener()
        {
            if (Object.FindFirstObjectByType<AudioListener>() != null)
            {
                return;
            }
            Camera camera = Camera.main;
            GameObject host = camera != null ? camera.gameObject : new GameObject("AudioListener");
            host.AddComponent<AudioListener>();
            Debug.Log("[audio] added the missing AudioListener to " + host.name);
        }

        private void PlayInternal(Sfx sfx, float pitch, float volume)
        {
            if (!_sfxEnabled || !_clips.TryGetValue(sfx, out AudioClip clip))
            {
                return;
            }
            // Round-robin over the pool: the oldest source is reused, so up to 8 effects overlap.
            AudioSource source = _sfxSources[_nextSource];
            _nextSource = (_nextSource + 1) % _sfxSources.Count;
            source.Stop();
            source.clip = clip;
            source.pitch = pitch;
            source.volume = SfxVolume * volume;
            source.Play();
            if (_fileJingles.Contains(sfx))
            {
                DuckMusic();
            }
        }

        /// <summary>Lowers the music under a jingle and brings it back smoothly; a second jingle restarts the timer.</summary>
        private void DuckMusic()
        {
            if (_musicSource == null || _music == null)
            {
                return;
            }
            if (_duckRoutine != null)
            {
                StopCoroutine(_duckRoutine);
            }
            _duckRoutine = StartCoroutine(Duck());
        }

        private IEnumerator Duck()
        {
            float start = _musicSource.volume;
            float ducked = _musicBaseVolume * DuckLevel;
            float t = 0f;
            while (t < DuckFadeOutSeconds)
            {
                t += Time.unscaledDeltaTime;
                _musicSource.volume = Mathf.Lerp(start, ducked, Mathf.Clamp01(t / DuckFadeOutSeconds));
                yield return null;
            }
            _musicSource.volume = ducked;
            yield return new WaitForSecondsRealtime(Mathf.Max(0f, DuckSeconds - DuckFadeOutSeconds));
            t = 0f;
            while (t < DuckFadeInSeconds)
            {
                t += Time.unscaledDeltaTime;
                _musicSource.volume = Mathf.SmoothStep(ducked, _musicBaseVolume, Mathf.Clamp01(t / DuckFadeInSeconds));
                yield return null;
            }
            _musicSource.volume = _musicBaseVolume;
            _duckRoutine = null;
        }

        /// <summary>
        /// Plays or pauses the loop to match the preference. Muting pauses (position kept) and
        /// unmuting resumes with UnPause, so toggling music never restarts the track.
        /// </summary>
        private void ApplyMusicState()
        {
            if (_musicSource == null || _music == null)
            {
                return;
            }
            if (_musicEnabled)
            {
                if (_musicPaused)
                {
                    _musicPaused = false;
                    _musicSource.UnPause();
                }
                else if (!_musicSource.isPlaying)
                {
                    _musicSource.Play();
                }
            }
            else if (_musicSource.isPlaying)
            {
                _musicPaused = true;
                _musicSource.Pause();
            }
        }

        private void OnDestroy()
        {
            if (_instance == this)
            {
                _instance = null;
            }
        }
    }
}
