using System.Collections.Generic;
using UnityEngine;

namespace BlastScale.Client.Audio
{
    /// <summary>Every sound effect the game can play (clips are generated by <see cref="SoundSynth"/>).</summary>
    public enum Sfx
    {
        UiClick,
        Pop,
        Invalid,
        Whoosh,
        CoinTick,
        CoinBurst,
        StarChime,
        WinJingle,
        LoseSting,
        ComboSwell,
        BoosterUse
    }

    /// <summary>
    /// Plays effects through a small pool of AudioSources (so overlapping pops never cut each
    /// other off) and loops the generated ambient music. Music and effects can be muted from the
    /// home screen; the choice is remembered in PlayerPrefs ("blastscale.music", "blastscale.sfx").
    /// A singleton created by the bootstrap; <see cref="Play(Sfx,float,float)"/> is safe to call
    /// before it exists (it simply does nothing).
    /// </summary>
    public sealed class AudioManager : MonoBehaviour
    {
        public const string MusicPrefKey = "blastscale.music";
        public const string SfxPrefKey = "blastscale.sfx";

        private const float MusicVolume = 0.35f;
        private const float SfxVolume = 0.8f;
        private const int SfxSourceCount = 8;

        private static AudioManager _instance;

        private readonly Dictionary<Sfx, AudioClip> _clips = new Dictionary<Sfx, AudioClip>();
        private readonly List<AudioSource> _sfxSources = new List<AudioSource>();
        private AudioSource _musicSource;
        private AudioClip _music;
        private int _nextSource;
        private bool _musicEnabled;
        private bool _sfxEnabled;

        public static AudioManager Instance => _instance;

        /// <summary>Creates the manager (and synthesises every clip) once; returns the existing one afterwards.</summary>
        public static AudioManager Ensure()
        {
            if (_instance == null)
            {
                var go = new GameObject("AudioManager");
                _instance = go.AddComponent<AudioManager>();
                _instance.Initialise();
            }
            return _instance;
        }

        /// <summary>Fire-and-forget effect; <paramref name="pitch"/> multiplies the clip's pitch.</summary>
        public static void Play(Sfx sfx, float pitch = 1f, float volume = 1f)
        {
            if (_instance != null)
            {
                _instance.PlayInternal(sfx, pitch, volume);
            }
        }

        /// <summary>Pop sound whose pitch grows with the group size (bigger groups sound brighter).</summary>
        public static void PlayPop(int groupSize)
        {
            float pitch = Mathf.Clamp(0.9f + (groupSize - 2) * 0.06f, 0.9f, 1.8f);
            Play(Sfx.Pop, pitch);
        }

        public bool MusicEnabled
        {
            get => _musicEnabled;
            set
            {
                _musicEnabled = value;
                PlayerPrefs.SetInt(MusicPrefKey, value ? 1 : 0);
                PlayerPrefs.Save();
                ApplyMusicState();
            }
        }

        public bool SfxEnabled
        {
            get => _sfxEnabled;
            set
            {
                _sfxEnabled = value;
                PlayerPrefs.SetInt(SfxPrefKey, value ? 1 : 0);
                PlayerPrefs.Save();
            }
        }

        /// <summary>Starts the ambient loop (respecting the mute preference); idempotent.</summary>
        public void StartMusic()
        {
            if (_music == null)
            {
                _music = SoundSynth.MusicLoop();
                _musicSource.clip = _music;
                _musicSource.loop = true;
                _musicSource.volume = MusicVolume;
            }
            ApplyMusicState();
        }

        private void Initialise()
        {
            _musicEnabled = PlayerPrefs.GetInt(MusicPrefKey, 1) == 1;
            _sfxEnabled = PlayerPrefs.GetInt(SfxPrefKey, 1) == 1;

            _clips[Sfx.UiClick] = SoundSynth.UiClick();
            _clips[Sfx.Pop] = SoundSynth.Pop();
            _clips[Sfx.Invalid] = SoundSynth.Invalid();
            _clips[Sfx.Whoosh] = SoundSynth.Whoosh();
            _clips[Sfx.CoinTick] = SoundSynth.CoinTick();
            _clips[Sfx.CoinBurst] = SoundSynth.CoinBurst();
            _clips[Sfx.StarChime] = SoundSynth.StarChime();
            _clips[Sfx.WinJingle] = SoundSynth.WinJingle();
            _clips[Sfx.LoseSting] = SoundSynth.LoseSting();
            _clips[Sfx.ComboSwell] = SoundSynth.ComboSwell();
            _clips[Sfx.BoosterUse] = SoundSynth.BoosterUse();

            for (int i = 0; i < SfxSourceCount; i++)
            {
                var source = gameObject.AddComponent<AudioSource>();
                source.playOnAwake = false;
                source.spatialBlend = 0f;
                _sfxSources.Add(source);
            }
            _musicSource = gameObject.AddComponent<AudioSource>();
            _musicSource.playOnAwake = false;
            _musicSource.spatialBlend = 0f;
        }

        private void PlayInternal(Sfx sfx, float pitch, float volume)
        {
            if (!_sfxEnabled || !_clips.TryGetValue(sfx, out AudioClip clip))
            {
                return;
            }
            // Round-robin over the pool: the oldest source is reused, so up to 8 effects overlap.
            AudioSource source = _sfxSources[_nextSource];
            _nextSource = (_nextSource + 1) % _sfxSources.Count;
            source.Stop();
            source.clip = clip;
            source.pitch = pitch;
            source.volume = SfxVolume * volume;
            source.Play();
        }

        private void ApplyMusicState()
        {
            if (_musicSource == null || _music == null)
            {
                return;
            }
            if (_musicEnabled)
            {
                if (!_musicSource.isPlaying)
                {
                    _musicSource.Play();
                }
            }
            else if (_musicSource.isPlaying)
            {
                _musicSource.Pause();
            }
        }

        private void OnDestroy()
        {
            if (_instance == this)
            {
                _instance = null;
            }
        }
    }
}
